### ISSUE TITLE
Twitter callback url error

### ISSUE THREAD

**Issue by sherin-mathew** [adamjmcgrath/react-native-simple-auth#100]
Login with twitter gives an error "**Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings**".
Previously this was working fine.
My configuration object looks like:
```
{
  appId: 'abc1234567890',
  appSecret: 'cba0987654321',
  callback: 'twitterappname://authorize',
}
```
Later I found that there happened a change recently in twitter api.

> https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

My callback url added in twitter app looks like "http://samplereactapp.com". This issue happens for both android an ios app. 
How can I resolve this issue? Please help me.

Thanks in advance.

**Comment by teilala** [comment]
same issues

**Comment by leventyildirim61** [comment]
+1

**Comment by joncursi** [comment]
👍

**Comment by kllm** [comment]
https://developer.twitter.com/en/docs/basics/callback_url.html

**Comment by og24715** [comment]
I was resolved it. thanks to @kllm

**Comment by CapitanRedBeard** [comment]
So the solution is to add `twitterappname://authorize` as an additional callbacks in your twitter app settings?

**Comment by og24715** [comment]
This issue seems to mean that it is caused by adding 'twitterappname://authorize' as a callback in the settings.
The solution is ...

> please use example:// as opposed to example://authorize

[Callback URL — Twitter Developers](https://developer.twitter.com/en/docs/basics/callback_url.html)
