### ISSUE TITLE
react native 0.56 not working in ios

### ISSUE THREAD

**Issue by krunaldodiya** [adamjmcgrath/react-native-simple-auth#105]
before i was using react native 0.55 and it was working perfect but today i upgraded to 0.56 and this is no more working in ios only, android is still working as usual but it seem ios has broken :)

**Comment by dennislaupman** [comment]
@kunaldodiya which version of 0.55 did you use? It seems that i'm facing the same problem...
Everything works well... after I kicked back from the browser (to authorize) to the app nothing happend...

the then function doesn't fired. 

`
simpleAuthProviders[provider](opts).then( (info) => {
 if(!info.user.error) {
         ...
          } else {
            this._error(info.user.error.message)
          }
      })
      .catch((error) => {
        this._error(error.message)
      });
`

no errors

My specs:
react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by krunaldodiya** [comment]
I am using 0.56.* react native, and issue has been resolved by updating gradle to 4.4.1, closing issue, feel free to reopen if you face any problem

**Comment by dennislaupman** [comment]
Grandle? Where can i find that? and how can I update that

**Comment by krunaldodiya** [comment]
@dennislaupman 

you can find gradle version in file :- android/gradle/wrapper/gradle-wrapper.properties

change
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5.1-all.zip
to
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4.1-all.zip

**Comment by dennislaupman** [comment]
Agggrrr.... :P adding this to the AppDelegate.m: 

`- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
`

did the trick ;)

The upgrade to 0.56 replaced the AppDelegate.m with a newer version,

A lot of thanks for your help!
