### ISSUE TITLE
Some installation notes

### ISSUE THREAD

**Issue by ktoh** [adamjmcgrath/react-native-simple-auth#14]
I had some trouble installing using the given directions in readme.md, so wanted to leave the following notes for others who might run across similar issues.
## Setting up the overall react native project

_i.e. setting up your application project that will eventually use react-native-simple-auth_
- There are currently two supported ways of starting a react-native project:  (1) set up via NPM, and (2) set up via CocoaPods.
- I tried both and found that the NPM approach is a lot more stable with the simple-auth library.
- The sequence I used was:
  1. Set up project using NPM via [official quick start](https://facebook.github.io/react-native/docs/getting-started.html#quick-start).
  2. Make sure the basic setup works before doing anything else
  3. Follow the react-native-simple-auth [install instructions](https://github.com/adamjmcgrath/react-native-simple-auth), with some adjustments below.
## Adjustments to react-native-simple-auth install process
- The [package.json](https://github.com/adamjmcgrath/react-native-simple-auth/blob/master/package.json) file in the react-native-simple-auth library is out of date...it points to an old, 0.4.4 version of react-native.  Since you've already installed react-native via `npm` above, change the following line in `react-native-simple-auth/package.json` under the "dependencies" section:
  -   ~~"react-native": "0.4.4"~~
  - "react-native": "/path/to/your/node_modules/react-native/directory"
  - ...in my case it was just `"react-native": "../react-native"`
- Before running `pod install` you may have to change your linker flags in your XCode project.  Open your XCode project, go to your target Build Settings -> Other Linker Flags, then double-click to add a new line and type in `$(inherited)`
  - This avoids an error message "OTHER_LDFLAGS..." during the pod install....see [this stackoverflow](http://stackoverflow.com/questions/18376416/the-target-overrides-the-other-ldflags-build-setting-defined-in-pods-pods/26077106#26077106) note.
- If your xcode project isn't in the root project directory, you will have to tell the `Podfile` where to find it.  Add the following line to Podfile:
  - `xcodeproj './path/to/your/.xcodeproj/project'`
- To avoid some warnings in the pod build and also framework reference warnings later on during the app build, I had to set my target IOS build to 8.0 instead of the 7.1 specified in this library:
  - In the Podfile, replace:
    - ~~platform :ios, '7.0'~~
    - platform :ios, '8.0'
  - In XCode -> Project -> Build Settings -> iOS Deployment Target, set value to iOS 8.0
- Once you drag `SimpleAuthWrapper.h` and SimpleAuthWrapper.m` into your XCode project, you may need to tell the project where to find files referenced inside these headers.  
  - In XCode, go to Project -> Targets -> (your app) -> Build Settings -> Header Search Paths
  - Double click and add the path to your Pods directory (in my case: `$(SRCROOT)/../Pods`), and set the dropdown on the right to `recursive`

Hope that helps

**Comment by adamjmcgrath** [comment]
Looks good thanks - would be great if you could raise a PR for improving the README

**Comment by cworsley4** [comment]
Hi @ktoh thanks for this. I'm still having one issue though maybe you could weigh in. I keep getting a build error siting, "framework not found Box". Any ideas?

**Comment by ktoh** [comment]
@cworsley4 what version of xcode are you using?

**Comment by cworsley4** [comment]
Version 7.0.1

**Comment by ktoh** [comment]
@cworsley4 perhaps try downgrading to 6.4 (https://developer.apple.com/downloads/)
There are some unresolved issues with swift code and deprecated libraries with react-native in Xcode 7.x.

**Comment by adamjmcgrath** [comment]
Thanks @ktoh for updating the README, will go ahead and close this issue

**Comment by thachp** [comment]
I am confused, where are the installation for NPM and CocoaPods?    The instructions in README seems mused together.  They are not clear.

I got to this point, do I have to add podfile and run pod install too?

```
npm install react-native-simple-auth

In XCode, in the project navigator right-click Libraries ➜ Add Files to [your project's name]

Go to node_modules ➜ react-native-simple-auth➜ iOS and add SimpleAuthWrapper.h and SimpleAuthWrapper.m
```

**Comment by adamjmcgrath** [comment]
> I am confused, where are the installation for NPM and CocoaPods? 

There are currently two supported approaches for installing `react-native`, npm or CocoaPods. The instructions recommend npm and provide a link to the react-native docs.

There's only one way to install `react-native-simple-auth`, install the javascript component of the library using npm (step 2 of https://github.com/adamjmcgrath/react-native-simple-auth#install). Install the iOS component of the library using steps 3 & 4. Then install the iOS library, SimpleAuth, using CocoaPods (steps 5, 6 and 7)

> I got to this point, do I have to add podfile and run pod install too?

Yep - follow steps 5, 6 and 7

**Comment by phonghho** [comment]
Is xcode 6.4 still the recommended version to use? Had several errors come up once the pods were installed. 

Thanks!

**Comment by phonghho** [comment]
Actually I figured it out. Adding the following to the pod file as referenced at https://github.com/calebd/SimpleAuth/issues/111 solves the swift errors.

pod 'Box', :head
pod 'Result', :head

**Comment by Banashek** [comment]
Thanks for the extra notes. Still getting the 'SimpleAuth/SimpleAuth.h' file not found error even after adding the directory to the build settings and following all of the steps above. 

Seems like it should be as straightforward as telling the project where to find the headers. I haven't done much ios programming. Is there more to defining header paths than just pointing to the directory where they should live?
