### ISSUE TITLE
Updating to a newer react-native (0.11.0).

### ISSUE THREAD

**Issue by allomov** [adamjmcgrath/react-native-simple-auth#15]
Hi, @adamjmcgrath. 

I'm trying to update react native version in order to use the latest version. I made it in a following way: I've created separate project called ReactNativeSimpleAuth using latest version of react-native and merged its content with react-native-simple-auth project. After that I needed to tweak Podfile and fixed a bug with ReactiveCocoa pod.

I perform all my work in this branch of my fork [allomov/react-native-simple-auth/tree/update-react](https://github.com/allomov/react-native-simple-auth/tree/update-react). And at this moment I have a problem with running the app: I get `EXC_BAD_ACCESS` error in RCTWebViewExecutor.m while running calling `[UIWebView new]`.

![screen with error](https://www.evernote.com/shard/s108/sh/6b8914ec-702e-4561-8ba1-7df570e79956/5272359cc5689392/res/e4912a6e-9be0-4c46-af4d-e619c35b647a/skitch.png)

Do have any thoughts about what does cause this error ?

Thank you,
Alex L.

**Comment by ktoh** [comment]
@allomov I haven't seen the `EXC_BAD_ACCESS` error before but I can confirm that I have react-native-simple-auth working with react-native 0.11.0.

I used the steps here: https://github.com/adamjmcgrath/react-native-simple-auth/issues/14

**Comment by adamjmcgrath** [comment]
> I get EXC_BAD_ACCESS error in RCTWebViewExecutor.m while running calling [UIWebView new].

Possibly related to facebook/react-native#2464

**Comment by adamjmcgrath** [comment]
> I get EXC_BAD_ACCESS error in RCTWebViewExecutor.m while running calling [UIWebView new].

Possibly related to https://github.com/facebook/react-native/issues/2464

**Comment by allomov** [comment]
@adamjmcgrath thank you for the clue. It started to fail right after I tried to debug code in Safary.
