### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by bhargavjoshi** [adamjmcgrath/react-native-simple-auth#16]
This library does not seem to support android, will it be supported in near future?

**Comment by adamjmcgrath** [comment]
Hi - yep, would be great to add Android support - haven't had a chance to look into it yet. Would gladly accept a Pull Request :)

**Comment by bhargavjoshi** [comment]
I am just starting out with react native and mobile development at the moment, so don't know how I can be helpful in this project.

**Comment by ktoh** [comment]
I'll need android support too, and will gladly help out but it'll be a couple months from now.

**Comment by rclai** [comment]
This library is nice. Looks like SimpleAuth doesn't support Android, but I found something that might be like it for Android. Is this the one?

https://github.com/3pillarlabs/socialauth-android

**Comment by adamjmcgrath** [comment]
Yes, that looks like it shares many of the features for Android that [SimpleAuth](https://github.com/calebd/SimpleAuth) does for iOS

**Comment by rclai** [comment]
If we decide to use the social auth android plugin in this project then that makes the naming of this package not make sense. It might need to be changed to something more generic perhaps?

Otherwise, I was thinking that making a separate package would make more sense but someone  had already taken react-native-social-auth.

**Comment by dmbrowne** [comment]
@rclai @adamjmcgrath are you guys giving it a go? I dont know Java AT ALL, so I can't help. But excited if you are indeed gonna implement it for android :)

**Comment by adamjmcgrath** [comment]
Hi @dmbrowne 

Not currently, but I think a friend of mine @jimenglish81, said he was going to take a look - so watch this space

**Comment by karthickvkumar** [comment]
Hi @adamjmcgrath , @jimenglish81 Thanks for this awesome library, It would be helpful if u provide android support.

**Comment by adamjmcgrath** [comment]
Hi, this is still in the works, I expect we'll have an update soonish

**Comment by austinkelleher** [comment]
+1 Would love to see this feature.

**Comment by anton6** [comment]
+1

**Comment by peterschmiz** [comment]
+1

**Comment by BigPun86** [comment]
+1

**Comment by amnevins** [comment]
+1

**Comment by shraddha1704** [comment]
+1 for android support

**Comment by pratyushsharma** [comment]
+1

**Comment by waleedarshad-vf** [comment]
+1 for android support

**Comment by waleedarshad-vf** [comment]
+1

**Comment by waleedarshad-vf** [comment]
Any alternate until this library support android?

**Comment by waleedarshad-vf** [comment]
+1

**Comment by waleedarshad-vf** [comment]
+1

**Comment by maiklez** [comment]
+1

**Comment by f4-labs** [comment]
- 1

**Comment by Spacelapp** [comment]
Update? :D

**Comment by adamjmcgrath** [comment]
I've been looking at this recently, I'll try and share something in the next week or two

**Comment by ddpdev** [comment]
+1

**Comment by Shinichi52** [comment]
+1

**Comment by dungvu-equix** [comment]
+1

**Comment by DeveloperAlly** [comment]
Any news on Android support cheers!

**Comment by adamjmcgrath** [comment]
I'm away on holiday at the moment and didn't get a chance to finish it before I left.

Have raised a pr #48 where you can follow the progress, I'll be picking it up again next week some time

**Comment by adamjmcgrath** [comment]
Android support added in [2.0.0](../releases/tag/2.0.0)

Take a close look at the install instructions, the library no longer uses the native iOS library or Pods so should be easier to set up.

Raise another issue if you run into any problems

**Comment by austinkelleher** [comment]
@adamjmcgrath Thanks for all of the effort you put into making this happen!
