### ISSUE TITLE
clarify Podfile instructions 

### ISSUE THREAD

**Issue by PalermoD** [adamjmcgrath/react-native-simple-auth#20]
```

xcodeproj 'ios/yourAppName.xcodeproj'
platform :ios, '7.0'
use_frameworks!

target 'yourAppName' do
  pod 'SimpleAuth/Facebook'
  pod 'SimpleAuth/GoogleWeb'
  pod 'SimpleAuth/Twitter'
  pod 'SimpleAuth/Instagram'
end

```

its not clear at first that you need to require the path and specify your app name how I specified it below.
This will solve 2 common errors 

```
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    xcodeproj 'path/to/Project.xcodeproj'
```

and 

```
[!] Unable to find a target named `ReactNativeSimpleAuth

```

**Comment by simchaWE** [comment]
Thanks

**Comment by adamjmcgrath** [comment]
The README has instructions adding the path to your project in the Podfile

"You may need to tell the podfile where to find your xcode project by adding the following to the podfile: xcodeproj './path/to/your/.xcodeproj/project'"
https://github.com/adamjmcgrath/react-native-simple-auth#install

Will update the example Podfile when I update react-native in the example app
