### ISSUE TITLE
Errors in Box and Result

### ISSUE THREAD

**Issue by aintnorest** [adamjmcgrath/react-native-simple-auth#21]
I'll start this could be an error with Pods since I've never used it before this. After installing everything and opening xcode with the .xcworkspace file I got a few errors in Box all four were simple syntax changes i suppose. toString the error said was changed to just String and the other one i can't remember. After i cleared those Results fails with a bunch of errors but I don't know swift and don't want to try messing with it.

**Comment by aintnorest** [comment]
Seems its caused by https://github.com/calebd/SimpleAuth/issues/113

So I just added pod 'ReactiveCocoa', '~>4.0.2-alpha-1' to the target do list in the Podfile

**Comment by adamjmcgrath** [comment]
ok thanks - will go ahead and close this issue, feel free to reopen if you think there's any work to be done in this library
