### ISSUE TITLE
Use with latest react native?

### ISSUE THREAD

**Issue by tgoldenberg** [adamjmcgrath/react-native-simple-auth#23]
It would be really nice if this was easy to use with current versions of React Native. I was unable to get the package working with the add-on installation instructions, and I would hope that there is a way to make it more easily integratable. Any timeline for this? Thanks!

**Comment by adamjmcgrath** [comment]
I haven't had much time to look at this lately - happy to accept Pull Requests though.

Are you getting any specific errors?

**Comment by ktoh** [comment]
+1 it'd be helpful to start collecting the errors here so we can figure out how to get compliance

**Comment by adamjmcgrath** [comment]
Just ran this with the latest version of react-native and experienced 1 issue to get it working, which I've fixed in #24 

You my need to do a `npm prune` after installing the latest version.
