### ISSUE TITLE
Promise.js naming collision

### ISSUE THREAD

**Issue by parmarnishant** [adamjmcgrath/react-native-simple-auth#25]
Error building DependencyGraph:
 Error: Naming collision detected: <<Projectpath>>/node_modules/react-native-simple-auth/node_modules/react-native/Libraries/Promise.js collides with <<Projectpath>>/node_modules/react-native/Libraries/Promise.js
Promise.js naming collision

**Comment by adamjmcgrath** [comment]
> /node_modules/react-native-simple-auth/node_modules/react-native/Libraries/Promise.js 

#24 should fix this - delete your `node_modules` directory and install the latest version

**Comment by davidchang** [comment]
@adamjmcgrath, could you make another release in npm? Last release (0.2.8) appears to be from August and, unless I'm mistaken, doesn't automatically pick up #24

**Comment by beinginorbit** [comment]
I can confirm this isn't in npm yet. Would be great to see an update.

**Comment by adamjmcgrath** [comment]
Sorry - been on holiday, 0.2.9 released

**Comment by beinginorbit** [comment]
Thanks! @adamjmcgrath what's the status of SimpleAuth as an iOS library you think? I couldn't get it to work even using your fork to fix the FB field issue.

**Comment by adamjmcgrath** [comment]
Np - not sure about SimpleAuth. Think it had some issues with Xcode 7. I'll see if I can get it running locally in the next couple of days

**Comment by beinginorbit** [comment]
@adamjmcgrath You mentioned the field issues here, just curious why it hasn't been merged into the repo calebd/SimpleAuth#109 hence my curiosity of it's status. I've never used this library though so I'm not sure what to expect. In general should this thing pop a webview/svc/etc. for each auth provider?

**Comment by adamjmcgrath** [comment]
> just curious why it hasn't been merged into the repo calebd/SimpleAuth#109 hence my curiosity of it's status

No idea why calebd/SimpleAuth#109 hasn't been merged - there hasn't been a lot of activity on that repo and I haven't really pushed it as I use an old Facebook API key that still uses a compatible version of the Graph API

> I've never used this library though so I'm not sure what to expect. In general should this thing pop a webview/svc/etc. for each auth provider?

Each provider is different, for example [Facebook](/calebd/SimpleAuth/tree/master/Pod/Providers/Facebook) uses iOS Social framework, [FacebookWeb](/calebd/SimpleAuth/tree/master/Pod/Providers/FacebookWeb) pops a WebView, and there's a PR to add Facebook SDK login calebd/SimpleAuth/pull/44

**Comment by davidchang** [comment]
@adamjmcgrath sorry for late response, many many thanks for updating to 0.2.9. npm installed and everything worked seamlessly.

**Comment by beinginorbit** [comment]
Okay. Honestly I got Facebook SDK working already (which uses like 3 different methods depending on availability) but was interested in this for the Twitter and Instagram (or to do all the things would be nice). 

Any thoughts on a viable solution for all forms of social auth?

**Comment by adamjmcgrath** [comment]
> but was interested in this for the Twitter and Instagram (or to do all the things would be nice)
> Any thoughts on a viable solution for all forms of social auth?

SimpleAuth supports Twitter and Instagram, and [lots of other social auth providers](https://github.com/calebd/SimpleAuth/tree/master/Pod/Providers)

SimpleAuth has Twitter support for iOS Social framework ("Twitter") and WebView ("TwitterWeb"), so you could create a solution that falls back to WebView if iOS Social framework is not available, something like

``` js
simpleAuthClient.authorize('twitter').then((info) => {
  let token = info.token;
  let name = info.name;
}).catch((error) => {
  simpleAuthClient.authorize('twitterWeb').then((info) => {
    let token = info.token;
    let name = info.name;
  })
});
```

SimpleAuth only has support for Instagram via a WebView.
