### ISSUE TITLE
'SimpleAuth/SimpleAuth.h'    -----   file is not found

### ISSUE THREAD

**Issue by psschethan** [adamjmcgrath/react-native-simple-auth#26]
i have done all the installation steps but im facing this issue -------  ''SimpleAuth/SimpleAuth.h'    -----   file is not found.

**Comment by adamjmcgrath** [comment]
Not sure, did you try looking at these steps as well: https://github.com/adamjmcgrath/react-native-simple-auth/issues/14 ?

Feel free to reopen if you still have issues, but add the full logs and a link to your project if possible
