### ISSUE TITLE
Linker command failed (XCode 7.2 + iOS 9.2) - framework Box not found

### ISSUE THREAD

**Issue by panw** [adamjmcgrath/react-native-simple-auth#30]
I have followed the instructions from the install guide and the [tips](https://github.com/adamjmcgrath/react-native-simple-auth/issues/14), but have had no luck setting up simple auth. I keep getting the linker issue.

The only difference between the guide is that I am using iOS 9.2. I've also tried doing it with iOS 8.4 as well, but it also did not work.

I have a Podfile with Box and Result installed as well following this [issue](https://github.com/adamjmcgrath/react-native-simple-auth/issues/21).

Here is a link to an example repo. Please let me know if I missed something?

[https://github.com/panw/simple-auth-setup](https://github.com/panw/simple-auth-setup)

**Comment by tuneZola** [comment]
+1, the instructions also need to be clearer and more descriptive. They appear to be out of date also, so if you are on the latest versions of Xcode, it will not work.

**Comment by adamjmcgrath** [comment]
Hi, I did the following
1. upgraded XCode to 7.2
2. cloned a fresh copy of your repo (https://github.com/panw/simple-auth-setup)
3. ran npm install  && pod install
4. open ./HiYa.xcworkspace

Then I was able to successfully build the project.

You could try quitting Xcode and erasing the files in your DeriveData folder at:

``` bash
~/Library/Developer/Xcode/DerivedData
```

**Comment by panw** [comment]
@adamjmcgrath thanks for having a look. I erased the Xcode files and everything worked. Feel free to link to this repo as a template code or example setup.
