### ISSUE TITLE
facebook login not working

### ISSUE THREAD

**Issue by 29er** [adamjmcgrath/react-native-simple-auth#31]
I am getting an error when I try to use facebook login, I have the facebook AppID set up correctly in my 'secrets' file.

Error:Error Domain=SimpleAuthErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x7facb04efef0 {Error Domain=com.apple.accounts Code=6 "(null)"}}

works fine with other channels.
any chance you can help me troubleshoot ?
thanks

**Comment by adamjmcgrath** [comment]
This is because the Facebook provider uses IOS social framework (I suspect the ones that were working use a WebView). See https://github.com/adamjmcgrath/react-native-simple-auth/issues/27#issuecomment-167402589

**Comment by 29er** [comment]
thanks!
