### ISSUE TITLE
Twitter Oauth Error

### ISSUE THREAD

**Issue by rileybracken** [adamjmcgrath/react-native-simple-auth#32]
I am trying to setup Twitter Oauth, and it is logging this error. `Object {description: "The operation couldn’t be completed. (com.apple.accounts error 6.)", code: 102}`

Is it waiting on this? https://github.com/calebd/SimpleAuth/pull/109
Because that only looks like Facebook stuff.

Any help would be great. Below is my code.

Thanks.

``` JavaScript
import simpleAuthClient from 'react-native-simple-auth';
import secrets from '../../secrets';

class Login extends Component {
  static propTypes = {};

  componentWillMount() {
    simpleAuthClient.configure(secrets);
  }

  login() {
    simpleAuthClient.authorize('twitter')
    .then((data) => {
      console.log(data);
    })
    .catch((error) => {
      console.log(error);
    })
  }

  render() {
    return (
      <View style={ styles.container }>
        <TouchableHighlight
          onPress={ () => this.login() }
        >
          <Text>Twitter</Text>
        </TouchableHighlight>
      </View>
    );
  }
}
```

**Comment by followbl** [comment]
you're probably doing it in the simulator...add your credentials in settings and you should be good.

**Comment by rileybracken** [comment]
Ok that is what I thought. I didnt realize you could add it in the sim and Im not by my phone currently. Thanks!
