### ISSUE TITLE
[Twitter] Auth sometimes returns Code 101

### ISSUE THREAD

**Issue by rileybracken** [adamjmcgrath/react-native-simple-auth#33]
Sometimes while working in simulator I get this error in the debugger:

`Response: (null) Error: Domain=SimpleAuthErrorDomain Code=101 "(null)" UserInfo={SimpleAuthErrorStatusCode=429}`

If I wait maybe 5 minutes it will come back and work just fine.

**Comment by adamjmcgrath** [comment]
The HTTP status 429 means  "Too Many Requests", you're probably being rate limited by the Twitter API (https://dev.twitter.com/rest/public/rate-limiting)
