### ISSUE TITLE
How would i revoke access on signout outside this.setState

### ISSUE THREAD

**Issue by miknonny** [adamjmcgrath/react-native-simple-auth#36]
Hi, 

@adamjmcgrath Thanks a lot for this awesome project. 
I wanted to confirm is there was a way user could signout by revoking access outside this.setState?

**Comment by adamjmcgrath** [comment]
Hi,

Not sure what "revoking access outside this.setState" means exactly but hopefully this should answer your question:

From the author of SimpleAuth https://github.com/calebd/SimpleAuth/issues/19#issuecomment-33102305

"Simple is designed to authenticate your users against a social service and give you their access tokens. What happens to those tokens after that is up to you. You can store them in the keychain, send them to your back end, make requests, etc. When you no longer need them, or when requested by the user, you should remove those tokens from your storage and update your interface."

Any other questions, let me know

**Comment by miknonny** [comment]
@adamjmcgrath Thanks a lot for taking time to explaining. I know better now.
