### ISSUE TITLE
Writing Tests

### ISSUE THREAD

**Issue by phonghho** [adamjmcgrath/react-native-simple-auth#37]
Hi,

I keep getting this error when I try to write tests and need to import a class that uses 'react-native-simple-auth'

/Users/***/application/node_modules/react-native-simple-auth/lib/simpleauthclient.js:3
let SimpleAuthWrapper = require('react-native').NativeModules.SimpleAuthWrapper;

I'm pretty new to writing tests for react native apps so any tips would be great!

Thanks!

**Comment by phonghho** [comment]
Forgot to mention that I'm using mocha chai for writing tests.

**Comment by adamjmcgrath** [comment]
You'll want to stub the `react-native` dependency in your tests when you import `react-native-simple-auth`. I use [proxyquire](/thlorenz/proxyquire), you can see how I do it here:

https://github.com/adamjmcgrath/react-native-simple-auth/blob/master/test/simpleauthclient.test.js#L15

**Comment by phonghho** [comment]
Ahh...I see now. Thanks! 

Here's how I did it if anybody else is looking for another example. Let me know if there is a better way to do this.

`import chai from 'chai';
import sinonchai from 'sinon-chai';
import proxyquire from 'proxyquire';
import sinon from 'sinon';

let expect = chai.use(sinonchai).expect;
let configureSpy;
let authorizeSpy;
let actions;

before(() => {
   configureSpy = sinon.spy();
   authorizeSpy = sinon.spy();
   actions = proxyquire('../authActions', {
     'react-native-simple-auth': {
       NativeModules: {
         SimpleAuthWrapper: {
           configure: configureSpy,
           authorize: authorizeSpy
         }
       },
       '@noCallThru': true
     }
   });
 });

 afterEach(() => {
   configureSpy.reset();
   authorizeSpy.reset();
 });

 after(() => {
   configureSpy = null;
   authorizeSpy = null;
   actions = null;
 });`

**Comment by phonghho** [comment]
Ahh...I see now. Thanks!
