### ISSUE TITLE
Twitter: No ActionSheet for multiple accounts on iPad?

### ISSUE THREAD

**Issue by burnsting** [adamjmcgrath/react-native-simple-auth#38]
This is a bit specific, but it seems to be broken nonetheless..

If you have multiple twitter accounts on an iPad, trying to login doesn't work because the actionsheet to pick your account doesn't show. The actionsheet does show on an iPhone.

Seems simpleAuthClient.authorize('twitter')... doesn't work at all. No error and no login info.

It might be related to this SimpleAuth issue, but I'm not sure:
https://github.com/calebd/SimpleAuth/issues/77

**Comment by adamjmcgrath** [comment]
Not sure there's a solution to this issue in this library, feel free to reopen if you disagree.

You could try falling to the TwitterWeb provider in these cases
