### ISSUE TITLE
Can't authenticate Twitter

### ISSUE THREAD

**Issue by chrbradley** [adamjmcgrath/react-native-simple-auth#39]
Hi,

I'm experiencing the same issue described here: https://github.com/adamjmcgrath/react-native-simple-auth/issues/27

Here's my error:

```
Error:Error Domain=SimpleAuthErrorDomain Code=102 "(null)" UserInfo=    {NSUnderlyingError=0x7fbf549b2d70 {Error Domain=com.apple.accounts Code=6 "(null)"}}
```

Following the suggested advice here https://github.com/adamjmcgrath/react-native-simple-auth/issues/25#issuecomment-166947111, I now get this error:

```
Exception 'There is no class registered to handle twitter-web requests.' was thrown while invoking authorize on target SimpleAuthWrapper with params (
    "twitter-web",
    259
)
```

Based on these instructions: https://github.com/calebd/SimpleAuth/wiki/Twitter, my current set-up looks like this:

```
  componentWillMount() {
    simpleAuthClient.configure({
      twitter: {
        consumer_key: 'XXXX',
        consumer_secret: 'XXXX',
      }
    }).catch((error) => {
      console.log('error: ', error);
    });

    simpleAuthClient.configure({
      'twitterWeb': {
        consumer_key: 'XXXX',
        consumer_secret: 'XXXX',
      }
    }).catch((error) => {
      console.log('error: ', error);
    });
  },

...

  authorizeTwitter() {
    simpleAuthClient.authorize('twitter').then((info) => {
      let token = info.token;
      let name = info.name;
    }).catch((error) => {
      console.log('error: ', error);
      simpleAuthClient.authorize('twitterWeb').then((info) => {
        let token = info.token;
        let name = info.name;
      });
    });
  },
```

and the pod file:

```
...
target 'pcrm' do
  pod 'SimpleAuth/Facebook'
  pod 'SimpleAuth/GoogleWeb'
  pod 'SimpleAuth/Twitter'
  pod 'SimpleAuth/TwitterWeb'
  pod 'SimpleAuth/Instagram'
  pod 'SimpleAuth/Tumblr'
  pod 'SimpleAuth/LinkedInWeb'
end
```

I've tried configuring and authorizing both `twitter-web` and `twitterWeb`, but it always complains that `There is no class registered to handle (twitter-web / twitterWeb) requests.`

Any ideas?

Thanks

**Comment by adamjmcgrath** [comment]
That error would suggest that the `TwitterWeb` provider isn't installed properly. In these cases I find that cleaning the `DerivedData` folder can help (https://github.com/adamjmcgrath/react-native-simple-auth/issues/30#issuecomment-175905697)

Also, it's `configure` and `authorize` `twitter-web` and you can pass 2 providers to `configure`

``` javascript
simpleAuthClient.configure({
  twitter: ....,
  'twitter-web': ...
}, ...);
```

**Comment by chrbradley** [comment]
Clearing out `~/Library/Developer/Xcode/DerivedData` worked. Thank you!

**Comment by rrakeshtech** [comment]
same issue after cleaning out ~/Library/Developer/Xcode/DerivedData also not working still facing same issue.

<img width="465" alt="screen shot 2016-05-22 at 3 39 31 pm" src="https://cloud.githubusercontent.com/assets/3204611/15456358/7130e308-2033-11e6-99ca-c857179d20f2.png">

am also facing build issue throwing this error 

<img width="1347" alt="screen shot 2016-05-22 at 3 41 17 pm" src="https://cloud.githubusercontent.com/assets/3204611/15456359/b015cf8e-2033-11e6-8c12-57a28624fcdd.png">

if i uncheck the target membership of SimpleAuth build is successful but twitter oauth is not working.

please help me to fix this issue
