### ISSUE TITLE
LinkedIn implementation

### ISSUE THREAD

**Issue by isaacvigil** [adamjmcgrath/react-native-simple-auth#42]
Hello,
when implementing oAuth (for LinkedIn) inside a React Native WebView Component, Once successfully logged in and the uri-redirect is initiated, how do I trigger and pass the token back into the non-WebView React Native Component or store it asyncStorage for future use. Either using Promises, async/await or any alternative method of delivery.
Thank you.

**Comment by adamjmcgrath** [comment]
Hi,

When you call `authorize` on the simpleauth client it returns a `Promise` that, if the authentication is successful, resolves with an object that contains the token and some other user info

``` js
simpleAuthClient.authorize('linkedin-web').then((info) => {
  let token = info.token;
  // Store the token somewhere
})
```

**Comment by isaacvigil** [comment]
Hello Adam,
That helped fix it.
Thank you.
