### ISSUE TITLE
Still SimpleAuth/SimpleAuth.h file not found

### ISSUE THREAD

**Issue by madvas** [adamjmcgrath/react-native-simple-auth#44]
Hi,

I added `$(SRCROOT)/../Pods` `recursive` into Header Search Path, but still get the error. I have existing Pods folder, with all files installed

my Podfile

```
xcodeproj 'ios/myapp.xcodeproj'

platform :ios, '8.0'
use_frameworks!

target 'myapp' do
  pod 'SimpleAuth/Facebook'
  pod 'SimpleAuth/GoogleWeb'
  pod 'SimpleAuth/Twitter'
  pod 'SimpleAuth/Instagram'
  pod 'SimpleAuth/Tumblr'
  pod 'SimpleAuth/LinkedInWeb'
end
```

Do you have any idea where might be a problem?

**Comment by madvas** [comment]
Okay I figured out I should've opened `.xcworkspace` file, insted of `xcodeproj`, but then I got error when trying to build `SimpleAuthTwitterProvider.m`

```
cocoa-oauth/GCOAuth.h file not found
```

When I remove twitter, tumblr dep and leave just FB and Google it builds

**Comment by virusss8** [comment]
I have the same problem. 
`cocoa-oauth/GCOAuth.h file not found`

**Comment by bbrock25** [comment]
Its related to this: https://github.com/calebd/SimpleAuth/issues/128

If you update your header search paths as described in the comments, it should clear that up. Make sure your using the pods target...

**Comment by adamjmcgrath** [comment]
Thanks @bbrock25 The advice in https://github.com/calebd/SimpleAuth/issues/128#issuecomment-243906678 resolved the issue for me
