### ISSUE TITLE
Receiving redirect_uri_mismatch

### ISSUE THREAD

**Issue by BigPun86** [adamjmcgrath/react-native-simple-auth#45]
Hey there. I am receiving below error message. Now i know that this should be fixed in google´s developer console but actually i have done this already. Maybe anyone has faced similar issue?

<img width="317" alt="screen shot 2016-05-30 at 10 47 14" src="https://cloud.githubusercontent.com/assets/7880624/15644571/26f5a9b4-2654-11e6-84c7-5af51c8a23d1.png">

**Comment by bberak** [comment]
Whilst I haven't read any documentation regarding a delay - it definitely took me about 3 hours after I added "http://localhost" to the Authorized redirect URIs list for this error to disappear.

**Comment by adamjmcgrath** [comment]
In the new version (2.0.0) you specify the `redirect_uri` differently (see [README](/adamjmcgrath/react-native-simple-auth/blob/master/README.md))

Give the new version a try and let me know if you run into issues
