### ISSUE TITLE
Unable to build example

### ISSUE THREAD

**Issue by 5nyper** [adamjmcgrath/react-native-simple-auth#47]
I can't seem to build the example you linked in your README. when I run "npm install" in the root dir the process loops doing this until the maximum call stack is exceeded:

<img width="1018" alt="screen shot 2016-12-23 at 8 44 25 am" src="https://cloud.githubusercontent.com/assets/9522710/21455467/5515cec2-c8ee-11e6-9949-b8e30e154616.png">

Any pointers?

**Comment by adamjmcgrath** [comment]
This sounds like an issue with npm - feel free to raise another issue if you run into any problems specific to the library
