### ISSUE TITLE
More Providers

### ISSUE THREAD

**Issue by adamjmcgrath** [adamjmcgrath/react-native-simple-auth#49]
- [x] GitHub
- [x] ~~Microsoft~~
- [ ] Dropbox
- [ ] Soundcloud
- [ ] Yahoo!
- [ ] Amazon
- [ ] Netflix
- [ ] Stack Exchange

**Comment by Gys** [comment]
LinkedIn would be great :-)

**Comment by adamjmcgrath** [comment]
Unfortunately, LinkedIn (and also Instagram, Mircrosoft and probably plenty of other providers) don't support custom schemes in the `redirect_uri` which makes it difficult to support for iOS.

There may be a workaround, using something like http://stackoverflow.com/a/39115316/2157755 but I was going to gauge interest in those providers before I made a decision about supporting them (I don't need them myself).

Happy to accept a PR if someone wanted to implement them.

**Comment by adamjmcgrath** [comment]
Actually, it looks like this can be achieved in javascript (https://facebook.github.io/react-native/docs/webview.html#onshouldstartloadwithrequest) so should be relatively straightforward

**Comment by Gys** [comment]
The problem and workaround on StackOverflow are ios specific. Does that mean the problem does not exist for Android ?

**Comment by adamjmcgrath** [comment]
Yep, Android accepts deeplinks with the http/https scheme: https://developer.android.com/training/app-indexing/deep-linking.html#adding-filters

**Comment by nickkapoor** [comment]
Adam:

Thanks for your library.  I was hoping you could shed some light on how to do deep linking. I am able to get the google and twitter pages to show up on my ios simulator. After a successful Login to google or twitter, I get an alert "Open this page in 'AwesomeProject'" (AwesomeProject is the name of my project). However, after I click OK, it takes me back to my application as opposed to the promise in my code.  

Secret for twitter


    twitter: {
        appId: 'XXXXXX',
        appSecret: 'YYYYY',
        callback: 'AwesomeProject://authorize',
    }


LoginTwitter(){
        twitter(secrets.twitter).then((info) => {
            console.log("I am logged into twitter");
            Alert.alert(
                'Authorized Twitter',
                "Getting to twitter"
            );
        }).catch((error) => {
            alert("Caught an error in mainpage.js"+error);
            // error.description
        });
    }

It seems the Alert.alert is not firing in the "then" promise. I must have missed something and I cannot for the life of me figure out what step I am missing.  The deep linking document from twitter (as reference), does not shed enough light as to what code I need to add in the AppDelegate.m and how the google/twitter/oauth Providers will be redirected to the simple auth software.  Additionally, I Xcode cannot find #import <React/RCTBundleURLProvider.h> (Will figure it).

I apologize if this is a newbie question.  However, any guidance would be greatly appreciated.  Thanks.

**Comment by jsbranco** [comment]
@nickkapoor  make sure you are listening to the callback https://facebook.github.io/react-native/docs/linking.html

Did you add these?
```
componentDidMount() {
  Linking.addEventListener('url', this._handleOpenURL);
},
componentWillUnmount() {
  Linking.removeEventListener('url', this._handleOpenURL);
},
_handleOpenURL(event) {
  console.log(event.url);
}
```

**Comment by nickkapoor** [comment]
Thanks for reaching out JSbranco

I did add the lines to the MainPage.js, which gets navigated to from the index.ios.js.  In index.ios.js I have the following code.   

I don't see these links firing.

export default class AwesomeProject extends Component {

    constructor(props) {

        super(props);
        this.state = {
            loading: false
        };
        console.log("Reaching the index.ios.js page"+props);
    }

    componentDidMount() {
        var url = Linking.getInitialURL().then((url) => {
            if (url) {
                alert('Initial url is: ' + url);
            }
        }).catch(err => console.error('An error occurred', err));
    }


    render() {
        return (
            <Navigator
                style={styles.container}
                initialRoute={{id: 'MainPage'}}
        renderScene={this.navigatorRenderScene}/>
    );
  }
// setup the navigation in the ios page
    navigatorRenderScene(route, navigator) {
        _navigator = navigator;

        switch (route.id) {
            case 'MainPage':
                return (<MainPage navigator={navigator} title="{string.WELCOME}" info="{route.info}"/>);
            case 'Login':
                return (<Login navigator={navigator} title="Login" />);
            case 'UserPage':
                return(<UserPage navigator={navigator} title="UserPage" />);
            case 'RegisterPage':
                return(<RegisterPage navigator={navigator} title="RegisterPage" />);
        }
    }
}



And then in the MainPage

export  default  class MainPage extends Component{

    constructor(props) {

        super(props);
        this.state = {
            loading: false
        };

        console.log("In mainpage"+props);
    }

    componentDidMount() {
        Linking.addEventListener('url', this._handleOpenURL);




 AsyncStorage.getItem("@SOMEKEY:key").then((value) => {
        if(value !=null){
          this.UserPage(value)
        }

    this.setState({"SOMEKEY:key": value});
}).done();
}

    _handleOpenURL(event) {
        console.log(event.url);
    }

**Comment by adamjmcgrath** [comment]
Hi,

The deep link listeners get added when you execute the login method (https://github.com/adamjmcgrath/react-native-simple-auth/blob/2.0.0/lib/platforms/react-native.js#L18) so you don't need to add them yourself.

> The deep linking document from twitter (as reference), does not shed enough light as to what code I need to add in the AppDelegate.m and how the google/twitter/oauth Providers will be redirected to the simple auth software. Additionally, I Xcode cannot find #import <React/RCTBundleURLProvider.h>

See the second point in the install setup (https://github.com/adamjmcgrath/react-native-simple-auth#install) which points to https://facebook.github.io/react-native/docs/linking.html (Note the section that starts "NOTE: On iOS you'll need to link RCTLinking to your project by following the steps described here")

**Comment by adamjmcgrath** [comment]
Also - if you have any other difficulties with the setup, can you raise a new issue - this issue is for something else

**Comment by nickkapoor** [comment]
Not a problem. I am good. Had to clean my simulator and get rid of junk and fix the AppDelegate. Your directions were spot on. Many thanks.

**Comment by aprout** [comment]
Instagram would be nice.

**Comment by jaggs6** [comment]
Slack would be useful

**Comment by nehvaleem** [comment]
+1 for instagram support

**Comment by alexandrzavalii** [comment]
+1 for Linkedin

**Comment by Arafath-misree** [comment]
how to add your own provider ??

**Comment by adamjmcgrath** [comment]
Closing, will open issues for requests for specific providers
