### ISSUE TITLE
Error with Facebook Login

### ISSUE THREAD

**Issue by mohammedibrahim** [adamjmcgrath/react-native-simple-auth#52]
Hello, 

I tried to login with facebook but it gives me this error 

http://imgur.com/a/zIeY8

Thanks

**Comment by adamjmcgrath** [comment]
You should have something like this in your `AndroidManifest.xml`
https://github.com/adamjmcgrath/ReactNativeSimpleAuthExample/blob/master/android/app/src/main/AndroidManifest.xml#L34

**Comment by nickkapoor** [comment]
Issues with fb login. I cannot enter fb1234567890(example) in the developers.facebook.com for android.  It throws an error: 
"Needs to contain only letters, numbers, and underscores in segments separated by dots. The first segment should start with a letter.
Tab to access contents in the dialog"

Do you have any other suggestions for the package name and what values would I enter in the secrets file for the callback for facebook.

Thanks

**Comment by adamjmcgrath** [comment]
You don't need to add Android, the iOS credentials will work for both https://github.com/adamjmcgrath/react-native-simple-auth#facebook

**Comment by nickkapoor** [comment]
It seems I may have an issue with the AndroidManifest.xml.  The package name is different from the bundle ID.  In the android I am not getting the hook back into the app.  It never gets to the then part for android, while its working for the ios.  If you could shed some more guidance, it would be greatly appreciated.  Thanks

 LoginFB(){

      facebook(secrets.facebook).then((info)=>{


            this.props.navigator.push({
                title: "Facebook",
                info: info,
                id: "Facebook",
                provider: "facebook"
            });

        })
    }


<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.awesomeproject"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="com.golive-entertainment.golive" />
          </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="fbXXXXXXXXXXXXX" />
          </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="AwesomeProject"/>
          </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by adamjmcgrath** [comment]
You need to [set the `launchMode` of `MainActivity` to `singleTask` in `AndroidManifest.xml`](https://github.com/adamjmcgrath/react-native-simple-auth/#install) eg. 
https://github.com/adamjmcgrath/ReactNativeSimpleAuthExample/blob/master/android/app/src/main/AndroidManifest.xml#L21

**Comment by nickkapoor** [comment]
Many thanks Adam. Greatly appreciated.  That did it.

**Comment by adamjmcgrath** [comment]
Great, no worries
