### ISSUE TITLE
Android Redirect

### ISSUE THREAD

**Issue by jainh** [adamjmcgrath/react-native-simple-auth#57]
Hi,
Same code works on iOS, but on android neither Google nor Facebook redirecting back to client app. I have added AndroidManifest.xml scheme as specified.

```
<activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="com.XXXXXXXXX" />
          </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="fbXXXXXXXXXXXXX" />
          </intent-filter>
      </activity>

```

I am using same  iOS AppId, Callback for Android (For Google, Facebook). Hopefully, same iOS credential for Google and Facebook works on Android ? Am i missing anything on Android ?

**Comment by adamjmcgrath** [comment]
> Hopefully, same iOS credential for Google and Facebook works on Android ?

Yes - you can use the same credentials

> Am i missing anything on Android ?

Your `AndroidManifest.xml` looks good, so I can't see any reason why the deep links back to the android app wouldn't work.

**Comment by himanshucricket** [comment]
Yes it didn't work, touch button action do bring Google and Facebook page login happen and consent page appear but would not return to the app , for Google it goes to Google page and Facebook after consent stay at white background. How should I debug it ?

**Comment by jainh** [comment]
@adamjmcgrath I tried your app `ReactNativeSimpleAuthExample` with my AppId, does not work either, not able to bring my app after consent page.

**Comment by jainh** [comment]
@adamjmcgrath So, here is an another news, i tried earlier with gynemotion emulator that had only web view tester client that was not working at all in redirecting back to the client app. However, i installed emulator using Android Studio that has chrome as well as web view tester, chrome does work on Android in redirecting back to app but not the web view tester.

**Comment by adamjmcgrath** [comment]
ok, thanks for checking. I'm not familiar with the web view tester client - do you mean the "Browser" app that comes on Android?

**Comment by jainh** [comment]
So the browser app (Chrome or Other browser) works fine but Webview client in emulator does not work.

**Comment by adamjmcgrath** [comment]
ok, thanks for the info - I'll leave this open in case someone has any insight on how to fix

**Comment by valinaga** [comment]
similar things happens to me. IOS works just fine.
On Android after returning from the FB page (closing the webview) it does not fire the callback.
Not even an error, nothing. 
Any idea?

**Comment by jainh** [comment]
@valinaga try with emulator that has native browser either chrome or something else, Google redirect does not work with webview user agent.

**Comment by valinaga** [comment]
@jainh I trust that the emulator works, but at the end, I need it to work on the device. Is there a way to trigger open the default browser instead of webview?
Thanks for help.

**Comment by adamjmcgrath** [comment]
@valinaga  - the library uses [Linking.openUrl](https://facebook.github.io/react-native/docs/linking.html#openurl) which should open the default browser on the device or emulator you are using for http/https links. What @jainh was suggesting was that you make sure you're using a device or emulator which doesn't have a webview client (apparently Genymotion does this?) as the default browser as there seems to be an issue with that.

If your issue is not that, you could check that you have `android:launchMode="singleTask"` in the activity tag of your `AndroidManifest.xml`, eg https://github.com/adamjmcgrath/ReactNativeSimpleAuthExample/blob/master/android/app/src/main/AndroidManifest.xml#L21

**Comment by valinaga** [comment]
@adamjmcgrath Thanks a lot! It's working now just fine.

**Comment by adamjmcgrath** [comment]
> chrome does work on Android in redirecting back to app but not the web view tester

Going to close this bug as I don't see myself adding support for the web view tester
