### ISSUE TITLE
net::ERR_UNKNOW_URL_SCHEME

### ISSUE THREAD

**Issue by cokealmonacid** [adamjmcgrath/react-native-simple-auth#59]
Make all the steps to install this repo on a react-native project, but get the following after authorize the app permissions:

![captura de pantalla 2017-02-27 a las 11 42 37](https://cloud.githubusercontent.com/assets/16389394/23365406/c62ff232-fce1-11e6-88aa-523686db1116.png)

Added the launchTask to the mainActivity in the AndroidManifest.xml, anyone can help me with this?

**Comment by DavidKongDesheng** [comment]
Got same issue, can share how to fix it?

**Comment by rdibona** [comment]
You also have to add an intent-filter to handle incoming links. Here is a FB example:

`       <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="fb904958326237050" />
        </intent-filter>
`
