### ISSUE TITLE
Undefined "_OBJC_CLASS_$_SimpleAuth" when running against 0.4.4 and 0.8.0-rc.2

### ISSUE THREAD

**Issue by psbanka** [adamjmcgrath/react-native-simple-auth#6]
Hey there. Thanks for making this library. It looks very promising!

However I am having some difficulty installing. I tried installing this in a vanilla `react-native` project, adding the `Podfile` as follows:

```
platform :ios, '8.0'

pod 'SimpleAuth/Facebook'
pod 'SimpleAuth/GoogleWeb'
pod 'SimpleAuth/Twitter'
pod 'SimpleAuth/Instagram'
pod 'SimpleAuth/Tumblr'
pod 'SimpleAuth/LinkedInWeb'
```

And adding the `SimpleAuthWrapper.h` and `SimpleAuthWrapper.m` projects to the file. After compiling, the project errors out with:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SimpleAuth", referenced from:
      objc-class-ref in SimpleAuthWrapper.o
     (maybe you meant: _OBJC_CLASS_$_SimpleAuthWrapper)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

and 

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SimpleAuth", referenced from:
      objc-class-ref in SimpleAuthWrapper.o
     (maybe you meant: _OBJC_CLASS_$_SimpleAuthWrapper)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas how to troubleshoot?

**Comment by adamjmcgrath** [comment]
Hi, I'll see if I can reproduce over the weekend. But you could try `platform :ios, '7.0'` - I remember having issues using with the ios version before

**Comment by psbanka** [comment]
No luck switching to 7.0.
Here are the steps I performed, just to be clear:

```
react-native init rnsa
cd rnsa

#Set up Podfile:
cat > Podfile <<End-of-message
platform :ios, '7.0'
pod 'SimpleAuth/Facebook'
End-of-message

# Set up package.json:
cat > package.json <<End-of-message
{
  "name": "rnsa",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "0.4.4",
    "react-native-simple-auth": "^0.1.2"
  }
}
End-of-message

rm -rf node_modules/
npm install
pod install
open rnsa.xcworkspace/
```

Then followed the rest of the steps in your `README.md` file to add the `SimpleAuthWrapper.h` and `SimpleAuthWrapper.m` libraries in.

Using
- cocapods `0.38.1`
- node `0.10.39` (also tried with io.js 2.3.4)

**Comment by psbanka** [comment]
Looks like I missed the `use_frameworks!` line in the `Podfile`.
Thanks!

**Comment by adamjmcgrath** [comment]
Ah cool, great thanks
