### ISSUE TITLE
Function doesn't work after callback

### ISSUE THREAD

**Issue by cokealmonacid** [adamjmcgrath/react-native-simple-auth#60]
After give the permissions to twitter  and comeback to the app, the app dont do nothing:

```
twLogin() {
		twitter({
		  appId: XXXXXXX,
		  appSecret: XXXXXXXXXXXX,
		  callback: 'ciudadfacilapp://'
		}).then((info) => {
			console.log('works!')
		}).catch((error) => {
			console.log(error)
		});
	}
```

call this function through a TouchableHighlight like this:

```
<TouchableHighlight style={styles.buttonLoginTw} onPress={() => this._twLogin()}>
         <Text style={styles.textLogin2}>Login con Twitter</Text>
</TouchableHighlight>
```

Any idea?

**Comment by adamjmcgrath** [comment]
Have you followed the instructions on setting up deep links for iOS and Android? https://github.com/adamjmcgrath/react-native-simple-auth#install

**Comment by cokealmonacid** [comment]
yes, try it but was thinking, maybe is the sdk of facebook, now i remove all and try to use this repo to login both (twitter and facebook)

**Comment by cokealmonacid** [comment]
Cleaned up the project, take away the FBSDK and still doesn't work, i make the setup, put the deep link in iOS and Android, click the login with twitter, give the permissions and comeback to the app but `console.log('works!')` dont work

**Comment by nabeelvalapra** [comment]
Can you show up your AndroidManifest.xml?

**Comment by cokealmonacid** [comment]
brrrpp! problem whit the linking in iOS, the problem was solved

**Comment by ozsirma** [comment]
How did you solve the problem for ios ? can you describe ?

**Comment by cokealmonacid** [comment]
This are all the steps that i did from the beginning: 
- Use yarn to add react-native-simple-auth
- Added the launchMode to my MainActivity of AndroidManifest.xml and added the deep link scheme too, like this:

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.ciudadfacilapp"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="ciudadfacilapp" />
        </intent-filter>
       <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="fb975638039115054" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService"/>
    </application>

</manifest>`

*If you see, i added the intent-filter for Twitter (ciudadfacilapp) and Facebook (fb975638039115054)

- Now on iOS added the next to my info.plist to add the deep link:

`
<key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>ciudadfacilapp</string>
        </array>
      </dict>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>fb975638039115054</string>
        </array>
      </dict>
    </array>
`
Now if you see there is a CFBundleURLSchemes for ciudadfacilapp (twitter) and for fb975638039115054.

- Then follow the steps in the react-native docs about deep linking (for iOS):
https://facebook.github.io/react-native/docs/linking.html --> Follow the steps to add RCTLinking to de AppDelegate.m like the example there.
![captura de pantalla 2017-03-02 a las 08 06 24](https://cloud.githubusercontent.com/assets/16389394/23504607/16cc95a8-ff1f-11e6-9bc2-5a279d4ac858.png)


This is my AppDelegate.m : 
`#import <React/RCTLinkingManager.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"CiudadFacilApp"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

// Only if your app is using [Universal Links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html).
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
  return [RCTLinkingManager application:application
                   continueUserActivity:userActivity
                     restorationHandler:restorationHandler];
}

@end
`
IMPORTANT NOTE: When you add the RCTlinkingManager.h like a import in your AppDelegate.m and give you a error just change it to <React/RCTLinkingManager.h>m if you dont get this library you can follow the steps described here to added https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

Hope this help you!

**Comment by ozsirma** [comment]
Thank you for your help. It works ! 👍
