### ISSUE TITLE
how to get the email on twitter

### ISSUE THREAD

**Issue by cokealmonacid** [adamjmcgrath/react-native-simple-auth#61]
Im getting the user data and the credentials of the user, but now need the email from twitter, the app is whitelisted but doesn't comes in the callback, any suggest?

**Comment by adamjmcgrath** [comment]
You'd need to pass `include_email` to the [verify_credentials.json](https://github.com/adamjmcgrath/react-native-simple-auth/blob/master/lib/providers/twitter.js#L25-L26) Twitter endpoint.

The library doesn't currently support this, see my comments: https://github.com/adamjmcgrath/react-native-simple-auth/issues/51#issuecomment-282138576 and https://github.com/adamjmcgrath/react-native-simple-auth/issues/53#issuecomment-281155537
