### ISSUE TITLE
Error: AppIds don't match

### ISSUE THREAD

**Issue by rustykey** [adamjmcgrath/react-native-simple-auth#63]
Hi, I got the error message, when I was trying to login with Facebook.
"Error: AppIds don't match"
Only I can get the admin user info who is registered as admin on Facebook.

        //for ios
        facebook({
            appId: '5549861946418XX',
            callback: 'fb5549861946418XX://authorize',
        }).then((info) => {
            console.log(info);
        }).catch((error) => {
            console.log(error);
        });

RN: 0.4.1
RNSA : 2.0.0

**Comment by adamjmcgrath** [comment]
That is an awful error message I'm afraid, if you log out `obj` in https://github.com/adamjmcgrath/react-native-simple-auth/blob/master/lib/providers/facebook.js#L30 you should get better information as to why your request to `https://graph.facebook.com/debug_token` has failed

**Comment by adamjmcgrath** [comment]
Going to close this, feel free to reopen if you're still having issues

**Comment by draftkraft** [comment]
I get the same error, when I try to authorise a tester (Facebook app role tester). The Facebook app is not yet public. When adding the person as admin it works.
