### ISSUE TITLE
Unable to get response after authentication

### ISSUE THREAD

**Issue by GrishmaM** [adamjmcgrath/react-native-simple-auth#65]
Trying for google and facebook oauth in IOS
i'm able to open the authentication page and after accepting the permissions for google/facebook i'm not getting any response neither the error nor data.
my app secrets
{
    google: {
        appId: 'my ios app id',
        callback: 'iOS URL scheme:/oauth2redirect',
    },
    facebook: {
        appId: 'my appid',
        callback: 'fb my appid://authorize',
    },
}; 

url schemas
-> identifier - Facebook  urlSchema - fb my app-id
-> identifier - google urlScheme - iOS URL scheme

where am i going wrong pls suggest solutions

Thank you in advance

**Comment by filiphosko** [comment]
To me it seems like a linking problem. Did you set up deep linking correctly (according to the docs [here](https://github.com/adamjmcgrath/react-native-simple-auth#google))?

**Comment by GrishmaM** [comment]
yes i did

**Comment by GrishmaM** [comment]
else can you specify the steps to be followed while linking so that i can cross-check

**Comment by filiphosko** [comment]
I meant if you followed [these](https://facebook.github.io/react-native/docs/linking.html) (the paragraph that begins with 'NOTE: On iOS') and [these](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking) steps carefully. And then of course creating [URL schemes](https://dev.twitter.com/cards/mobile/url-schemes).

**Comment by GrishmaM** [comment]
yup i did all those steps.

**Comment by adamjmcgrath** [comment]
Would need some more information to help, can you provide a link to the project?

**Comment by GrishmaM** [comment]
i used react-native-gogle-signin and its working
