### ISSUE TITLE
Facebook error: AppIds don't match.

### ISSUE THREAD

**Issue by nehvaleem** [adamjmcgrath/react-native-simple-auth#67]
I've stumbled upon weird error. I've created an app on facebook and set up provider for facebook. If i try to login with my account (the same wchich I've used to create the app) it works fine. But on another account I am getting error: AppIds don't match. I've already publish my app and the id doesn't changed.

I would be very grateful for any help.

**Comment by adamjmcgrath** [comment]
That's a bad error message, if you follow these steps you'll get a better one https://github.com/adamjmcgrath/react-native-simple-auth/issues/63#issuecomment-284023592

**Comment by nehvaleem** [comment]
Yeah, i've figured :)

I've added some logging before error is thrown and detailed message is:

> "(#100) You must provide an app access token or a user access token that is an owner or developer of the app"

Which seems to make more sense since I can login with account that created app. Problem with all the other accounts. I don't know why facebook provider uses some kind of debug token? Isn't it only allowed for app developers or something?

**Comment by nehvaleem** [comment]
okay, I've discovered that when you use app access token https://developers.facebook.com/docs/facebook-login/access-tokens#apptokens then you can debug other tokens. So i think it should be passed down to provider from options. What do you think? Sadly I am too bad at functional programming and ramda is overwhelming for me right now so I won't even try to submit a PR :(

**Comment by nehvaleem** [comment]
cc: @adamjmcgrath

**Comment by adamjmcgrath** [comment]
Looking at the docs for `debug_token`, it shouldn't be used in this context at all - I should just get rid of https://github.com/adamjmcgrath/react-native-simple-auth/blob/master/lib/providers/facebook.js#L41-L43

I'll try and take a look at it in the next few days

**Comment by nehvaleem** [comment]
Awesome! Can't wait :)

**Comment by adamjmcgrath** [comment]
Published react-native-simple-auth@2.0.1
