### ISSUE TITLE
Issue with Example Project on iOS simulator 

### ISSUE THREAD

**Issue by roshangm1** [adamjmcgrath/react-native-simple-auth#69]
Safari cannot open the page because the address is invalid.
I get this error after giving permission to app for log in with facebook.

**Comment by sattaman** [comment]
I'm finding the same, links with the dot in don't seem to be accepted

**Comment by mirrorshades** [comment]
Did you configure your info.plist by copying and pasting?

`<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fb397780500xxxxxx</string>
  </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>397780500xxxxxx</string>
<key>FacebookDisplayName</key>
<string>App Name</string>` 

If so I ran into this problem too.

I would try doing it through Xcode instead. Keeping it very simple.
![image](https://cloud.githubusercontent.com/assets/2566674/24523041/bd30cf6c-155f-11e7-934e-15cadd166009.png)

Target App > Info > URL Types and the click the `+`

**Comment by adamjmcgrath** [comment]
Feel free to reopen if that suggestion doesn't work for you
