### ISSUE TITLE
Unable to resolve module NativeModules from /path/to/react-native-simple-auth/lib/simpleauthclient.js

### ISSUE THREAD

**Issue by jedlau** [adamjmcgrath/react-native-simple-auth#7]
After updating to react-native from 0.6.0 to 0.8.0, I started getting this error when building the main.jsbundle (`react-native bundle`):

```
Unable to resolve module NativeModules from <path/to/app>/node_modules/react-native-simple-auth/lib/simpleauthclient.js
```

I think this is related to https://github.com/facebook/react-native/issues/1808.

This comment provides a solution, which seems to work for me: https://github.com/facebook/react-native/issues/1808#issuecomment-117286723

Will send a pull request.

**Comment by adamjmcgrath** [comment]
Cheers for that, will publish 0.2.0 on npm shortly then close this off.

**Comment by jedlau** [comment]
Thanks for your help, Adam! And thanks for putting this package together.
Very useful.

**Comment by YonasBerhe** [comment]
I know this is a different repo, but the issue I'm having is relatively the same @adamjmcgrath https://github.com/naoufal/react-native-speech/issues/8
