### ISSUE TITLE
Does not get callback response(userInfo) in ios app

### ISSUE THREAD

**Issue by kailash-g** [adamjmcgrath/react-native-simple-auth#78]
Hi Team,

Does not get callback response(userInfo) in ios App, Its Working fine in Android App.

Even Safari open and validate email and get back to my App but does not call "then((info)" in IOS App.

My Code is below : 
google({
				appId: `${Config.GOOGLE_SOCIAL_SIGNIN_APPID}`,
				callback: 'com.prettysecrets.shopbra:/oauth2redirect',
			}).then((info) => {
				console.log('customerinfo======', info);
				customer = info;
			}).catch((error) => {
				console.log('==GOOGLE SIGN IN=================', error);
				helper.showValidationError(`${errorMessages.SOMETHING_WENT_WRONG}`);
			});

**Comment by masiamj** [comment]
Same issue. Any ideas?

**Comment by zoecarver** [comment]
me too, any help?

**Comment by anaerobic** [comment]
Follow the instructions at https://facebook.github.io/react-native/docs/linking.html for Universal Links, triple check everything is correct.

Be careful to match your version of react-native to the docs. 👍

**Comment by rvirani1** [comment]
Still having the same issue.

**Comment by jveryl** [comment]
same problem.
sad :(

**Comment by Viral-Inc** [comment]
I have the same issue trying this with an Expo react-native app, but Expo doesn't yet support Universal links so I don't think it'll work for me :(

**Comment by adamjmcgrath** [comment]
This looks like a setup issue, happy to reopen if you have any more info
