### ISSUE TITLE
Twitter Callback Not Firing

### ISSUE THREAD

**Issue by masiamj** [adamjmcgrath/react-native-simple-auth#80]
First off, great work on the library and documentation, looks really neat. Unfortunately, when I make the Twitter call, my app is not getting any Promise resolution.

Here's the code:

twitter({
        appId: 'GQ**********',
        appSecret: 'XW********',
        callback: '******',
      })
        .then((info) => {
          console.log(info);
        })
        .catch(console.error);

I also set up Linking listeners:

Linking.getInitialURL()
.then((url) => {
  console.log(url);
})
.catch(console.error);

Linking.addEventListener('url', (url) => {
  console.log(url);
});

Here's a quick video: http://quick.as/8xJ8h8mjX

Any ideas what's going on? Any help would be greatly appreciated!

**Comment by zoecarver** [comment]
I am not sure if this is the same thing that is happening to you, but for me adding: 
`#import <React/RCTLinkingManager.h>`
...
```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
```
To your AppDelegate.m file fixed it.

**Comment by masiamj** [comment]
I already have that, but unfortunately, still not getting anything in the callback.

**Comment by masiamj** [comment]
@adamjmcgrath Do you have any input here? Been struggling with this for several days and haven't been able to make any progress, unfortunately.

**Comment by zoecarver** [comment]
sorry, I can't help you any more than that. But it looks like you found the problem (given that you closed the issue). Would you mind writing a quick comment sharing what the problem was for others if they have the same issue?
