### ISSUE TITLE
Configurable scope for google

### ISSUE THREAD

**Issue by tamirla** [adamjmcgrath/react-native-simple-auth#83]
Trying to use google spreadsheets api after using the module for google authentication I got in response:

"Request had insufficient authentication scopes."

"PERMISSION_DENIED"

I had to change scope definition to following in lib/providers/google.js:

const SCOPE = 'https://www.googleapis.com/auth/spreadsheets';

In order to fix this problem.

Is it possible to extend the library so scope variable will be configurable from outside ?

Thanks

**Comment by adamjmcgrath** [comment]
fixed by #92
