### ISSUE TITLE
[Twitter] application opened in browser instead back to apps after authentication.

### ISSUE THREAD

**Issue by hophoppoppop** [adamjmcgrath/react-native-simple-auth#85]
So, i use twitter authentication. But, everytime it redirected to apps it's restart the apps.

**Comment by hophoppoppop** [comment]
Okay, so it's not restarted but it more like it opened new in browser. I still don't know why it opened in browser instead back to apps.

**Comment by adamjmcgrath** [comment]
This sounds like an issue with your launchMode setting in Android (assuming you're trying to setup Android - it's hard to tell from the information you've provided)
https://github.com/adamjmcgrath/ReactNativeSimpleAuthExample/blob/master/android/app/src/main/AndroidManifest.xml#L21
