### ISSUE TITLE
[Twitter] Deep Linking to Allow Redirect After Auth

### ISSUE THREAD

**Issue by KeanuTomatoMomotaro** [adamjmcgrath/react-native-simple-auth#87]
I'm trying to implement a twitter auth by following the steps in the 'install' portion as well as the solutions proposed in related closed issues.

The problem i'm facing is that the application does not redirect back after authorizing twitter through the mobile web browser (chrome on physical device, along with webview browser on the emulator device).

I've unlocked the callback locking from my Apps.twitter.com page, renamed my react-native application to match the twitter app name on the site as well, and have edited the android manifest file.

Below are some of my files and settings

**Manifest**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.bukamata"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:launchMode="singleTask"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="BukaMata"/>
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```
**App.js snippet**
```
getTokens(){
  twitter({
      appId: 'xxx',
      appSecret: 'yyy',
      callback: 'BukaMata://authorize',
    }).then((info) => {
      console.log(info)
    }).catch((error) => {
      console.log(error)
    });
  }
```
@adamjmcgrath keeps mentioning deep linking, what does this mean? i even tried resolving through the adb manager to no avail...yet.

**Comment by codesinghanoop** [comment]
I'm stuck here please help me not able to perform deep linking.

**Comment by MorcosS** [comment]
refer to this to apply deep linking: https://reactnavigation.org/docs/deep-linking.html, I am trying it will provide some code once this works for me

**Comment by artem-romanov** [comment]
@MorcosS Confirm that. I'm using the react-navigation and after I setup deeplinking for react-navigation twitter works ok.
