### ISSUE TITLE
[Android] - promise never resolved

### ISSUE THREAD

**Issue by KisaneNeko** [adamjmcgrath/react-native-simple-auth#89]
I have my facebook and google configs set up so they work perfectly on iOS, but I'm having problems running it on Android. The promise is never resolved (by promise I mean result of `google(config) and facebook(config)`).
I do have intents configured correctly as my app opens, and I do have `launchMode` set as `singleTask` on my MainActivity. I test it on virtual device which opens chrome.

One more interesting thing, is that I tried to add `Linking.addEventListener('url', callback)` manually in `componentDidMount` of my component, and on iOS it's called when app is brought back after reopening app when users logs into social media, but it doesn't run at all on Android.

When I remove `launchMode`, I can get authentication token from `Linking.getInitialURL` correctly, but promise created by this library never resolves in this case either. Any ideas what I might be missing here?

**Comment by leowilsoncordones** [comment]
I am facing similar issue. On iOS works perfectly, but on Android the promise never resolves.

**Comment by codesinghanoop** [comment]
@adamjmcgrath i'm facing the same issue. NEED HELP

**Comment by adamjmcgrath** [comment]
Looks like a setup issue, feel free to share your project with this thread. Closing for now
