### ISSUE TITLE
Adding custom Providers

### ISSUE THREAD

**Issue by irfman12** [adamjmcgrath/react-native-simple-auth#90]
nice Libraries, can you guide us on how to add a custom provider, by either forking the code.

the custom provider requires additional query parameters to authorize code flow, and access token flow which makes it difficult to re-use most great libraries out there.

**Comment by adamjmcgrath** [comment]
Hi, you should be able to compose your own custom providers from the library without forking it, eg


```js

import login from 'react-native-simple-auth/lib/login';
import * as platform from 'react-native-simple-auth/lib/platforms/react-native';

const myProvider = { // see facebook provider for oauth2 example
  authorize: ...,
  identify: ...
};

export const myLogin = login(myProvider, platform);
```

**Comment by irfman12** [comment]
I need to add to do PKCE flow with Oauth where I need to send code challenge and code verifier, can I still do that with your example?
